name: "Bug Report"
description: "Report a bug in Ody"
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      placeholder: "Describe the bug"
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: "1. Import ody...\n2. ..."
  - type: textarea
    id: code
    attributes:
      label: Example Code
      render: typescript
      placeholder: |
        ```ts
        ody.string().parse(123);
        ```
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: "Node version, TS version, OS…"
