name: "Feature Request"
description: "Propose a new feature for Ody"
labels: ["feature"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: "Ex: Add object() with full TypeScript inference"
  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      placeholder: "Explain the expected behavior, API design, and constraints..."
      render: markdown
  - type: textarea
    id: api
    attributes:
      label: API Proposal
      placeholder: |
        Example:
        ```ts
        const user = ody.object({
          name: ody.string(),
          age: ody.number().min(18),
        });
        ```
      render: markdown
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Tests planned
        - label: Documentation planned
        - label: DX impact considered
